In [1]:
import numpy as np

In [3]:
arr = np.array([1 , 2 , 3 , 4])
print(arr)

[1 2 3 4]


In [6]:
a = [1 , 2 , 3.5 , 4 ]
a

[1, 2, 3.5, 4]

In [7]:
np.array(a)

array([1. , 2. , 3.5, 4. ])

In [ ]:
l = [[1 , 2] , [3 , 4] , [5 , 6]] #VECTOR
l 

[[1, 2], [3, 4], [5, 6]]

In [ ]:
np.array(l) #MATRIX

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr = np.arange(1 , 11 , 2)
arr

array([1, 3, 5, 7, 9])

In [13]:
l = np.zeros(6)
l

array([0., 0., 0., 0., 0., 0.])

In [14]:
ar = np.zeros((6 , 6))
ar

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr = np.ones((6 , 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
arr = np.linspace(1 , 11 , 3)
arr

array([ 1.,  6., 11.])

In [26]:
np.random.rand(10)

array([0.39671352, 0.29105964, 0.01586897, 0.97918763, 0.78862608,
       0.20118103, 0.66561431, 0.53111108, 0.01493624, 0.67570789])

In [30]:
np.random.randn(10)

array([ 0.22250765,  2.01536639,  0.51508787,  0.44044598,  0.87895343,
       -0.210245  , -0.19282648,  0.2573762 , -0.99858345,  0.34948178])

In [ ]:
np.random.randint(6)

4

In [34]:
np.random.randint(10 , 20 , 10)

array([12, 18, 16, 11, 17, 10, 12, 17, 14, 19])

In [35]:
num = np.array([[1 , 2] , [3 , 4] , [5 , 6]])
num

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
num.shape
num.size
num.dtype

dtype('int32')

In [42]:
print(num.min())
print(num.max())

1
6


In [43]:
num.sum()

21

In [45]:
np.sum(num , axis = 0)

array([ 9, 12])

In [46]:
np.sum(num , axis = 1)

array([ 3,  7, 11])

In [48]:
num.mean()

3.5

In [50]:
num.std()

1.707825127659933

In [51]:
num.argmax()

5

In [53]:
nums = np.arange(1 , 31)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [59]:
nums = nums.reshape(6 , 5)

In [60]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# INDEXING AND SLICING

In [61]:
x = np.arange(11 , 21)
x

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
print(x[5])

16


In [66]:
print(x[5 : 0 : -1])

[16 15 14 13 12]


In [68]:
a = np.arange(1 , 31).reshape(6 , 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [76]:
sliced = a[0 : 2 , 1 : 3]
sliced

array([[2, 3],
       [7, 8]])

In [77]:
a[3 : 6 , 3 : 6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [79]:
p = np.arange(11 , 21)
p

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [81]:
bool_index = p % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [82]:
p = p[bool_index]
p

array([12, 14, 16, 18, 20])

# ARRAY OPERATIONS

In [87]:
a1 = np.array([1 , 2 , 3 , 4 , 5])
a2 = np.array([6 , 7 , 8 , 9 , 10])
print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [89]:
arr2 = print(a1 + a2)

[ 7  9 11 13 15]


# BROADCASTING

In [90]:
l = [10,20,30,40]
arr = np.array(l)

In [92]:
l = [x + 10 for x in l]

In [93]:
arr + 10

array([20, 30, 40, 50])

In [96]:
o = np.arange(1 , 26).reshape(5 , 5)
o

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [97]:
o + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

# DEEP AND SHALLOW COPY

In [98]:
a = np.arange(1 , 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [100]:
slicee = a[0 : 5]
slicee

array([1, 2, 3, 4, 5])

In [102]:
slicee = slicee * 10
slicee

array([10, 20, 30, 40, 50])

In [103]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [104]:
a[4 : 6] * 10

array([50, 60])

In [105]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#   MATRIX OPERATIONS


In [108]:
A = np.arange(1 , 5).reshape(2 , 2)
B = np.arange(5 , 9).reshape(2 , 2)

In [109]:
A

array([[1, 2],
       [3, 4]])

In [110]:
B

array([[5, 6],
       [7, 8]])

In [111]:
A * B

array([[ 5, 12],
       [21, 32]])

In [112]:
A @ B

array([[19, 22],
       [43, 50]])

In [113]:
A.T

array([[1, 3],
       [2, 4]])

#                                              STACKING


In [119]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [120]:
b = np.array([5, 6, 7, 8])
b

array([5, 6, 7, 8])

In [121]:
np.vstack((a , b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
np.hstack((a , b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
np.column_stack((a , b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#                               SPLITTING

In [125]:
c = np.arange(16).reshape(4 , 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
np.hsplit(c , 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [127]:
np.vsplit(c , 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# EXERCISES

In [ ]:
# VALID SUDOKU  RULES: 1. every row and col has sum 45 and every 3 X 3 box has 45 sum

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [131]:
col_sum = np.sum(s , axis = 0)
row_sum = np.sum(s , axis = 1)
print(col_sum)
print(row_sum)

[45 45 45 45 45 45 45 45 45]
[45 45 45 45 45 45 45 45 45]


In [135]:
for i in range(0 , 9 , 3):
    for j in range(0 , 9 , 3):
        n = sum(s[i:i+3 , j:j+3])
        if(sum(n) != 45):
            print("NOT VALID")
            break
            
    
else:
    print("VALID")

VALID


In [174]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [138]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [143]:
#Find the average age of students.
d1 = data[: , 0]
d1.mean()

18.4

In [145]:
#Extract Math marks of all students.
maths_marks = data[ : , 1:2]
maths_marks

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [147]:
#Find the highest Science mark.
science_marks = data[: , 2:]
science_marks
print(science_marks.max())

95


In [ ]:
#Get details of the student who scored more than 90 in Math.
d1 = data[: , 1] > 90
d1
data[d1]

array([[19, 92, 88],
       [20, 90, 85]])

In [159]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [160]:
#Increase Math marks of all students by 5.
data[: , 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [162]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [164]:
#Calculate the average marks in each subject (column-wise mean).
data[: , 1:]

array([[85, 78],
       [92, 88],
       [76, 95],
       [65, 70],
       [90, 85]])

In [165]:
np.mean(data[: , 1:] , axis = 0)

array([81.6, 83.2])

In [169]:
#Get data of students who scored at least 80 in both subjects.
data[(data[: , 1] >= 80) & (data[: , 2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [175]:
#Replace all Science marks < 75 with 0.
data[: , 2][data[: , 2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])